### ISSUE TITLE
Lua error on startup

### ISSUE THREAD

**Issue by andrewcalimlim** [Hoshikara/Nightfall#1]
![error](https://i.imgur.com/nlPwVya.png)

**Comment by Hoshikara** [comment]
the usage of that file has been removed, this shouldn't be an issue if your game is up to date:

https://github.com/Drewol/unnamed-sdvx-clone/commit/1b5a0af03d899969e030c49dbbb7cbde3b7f228b#diff-0b295c0c920fae84f49bfb0686c39b1fL1266
