### ISSUE TITLE
Near Error Display in Practice mode

### ISSUE THREAD

**Issue by HamiltonianHamiltonian** [Hoshikara/Nightfall#17]
After updating the usc version, the feature that shows near and error in Practice mode (which is the cumulative total one shown on the left side after playing) is no longer available. Where can I activate that feature? And is this a specification?

**Comment by Hoshikara** [comment]
Addressed in version [`1.5.2`](https://github.com/Hoshikara/Nightfall/releases/tag/1.5.2)
