### ISSUE TITLE
Crash When Mashing in Song Loading Screen

### ISSUE THREAD

**Issue by 88botong** [Hoshikara/Nightfall#19]
After the v.0.6.0 update, mashing buttons repeatedly will crash the game on the song loading screen

1. Start a song
2. When the song is loading, press the buttons quickly

OS: Windows 10

Log:
[15:43:34][Error] Lua error on calling button_hit: ...sc-game-v0.5.0\skins/Nightfall-main/scripts/gameplay.lua:106: attempt to index a nil value (upvalue 'hitDeltaBar')
[crash.txt](https://github.com/user-attachments/files/16021595/crash.txt)

**Comment by Hoshikara** [comment]
Should be fixed in https://github.com/Hoshikara/Nightfall/releases/tag/1.5.5, please give it a try and see if the issue persists

**Comment by 88botong** [comment]
![crash](https://github.com/Hoshikara/Nightfall/assets/34149882/ecc40693-7329-4d0c-95bf-4f1ff22e89a6)
The issue persists

**Comment by 88botong** [comment]
Nevermind, the issue is resolved after redoing all patches until 1.5.5
