### ISSUE TITLE
Error when scrolling past first/last index while sorting

### ISSUE THREAD

**Issue by shrublet** [Hoshikara/Nightfall#2]
![image](https://user-images.githubusercontent.com/63182228/100262196-aafaca00-2f00-11eb-874f-816192019a33.png)

Fix is probably simple, but just thought I'd let you know in case you weren't aware. You can recreate by trying to sort and then scrolling up past the first option or down past the last option.

**Comment by Hoshikara** [comment]
https://github.com/Hoshikara/Nightfall/commit/4369ba798b2dc096f4945a94d3a8e8e7ab682e02
