### ISSUE TITLE
Folder scrolling feature

### ISSUE THREAD

**Issue by Gaabbu** [Hoshikara/Nightfall#4]
### It's kind of hard to go through my songs folders, I wonder if adding some sort of scrolling to it would be too hard?

![image](https://user-images.githubusercontent.com/64439196/101244946-47368500-36e8-11eb-8a40-b84b88c5ccdc.png)

**Comment by Hoshikara** [comment]
Added in https://github.com/Hoshikara/Nightfall/commit/3e4d66a2e9cd5f0eb8215b3d8845f15c9fbe8970
