### ISSUE TITLE
Best 20/50 label text gets cut off in third column

### ISSUE THREAD

**Issue by shrublet** [Hoshikara/Nightfall#5]
consistently happens in third column , but otherwise looks good (it's fine in the song info panel). resolution is 1440p 16:9 fullscreen
![image](https://user-images.githubusercontent.com/63182228/101261351-7bf80b80-36eb-11eb-9d9d-3d67cf282941.png)

**Comment by Hoshikara** [comment]
Fixed in https://github.com/Hoshikara/Nightfall/commit/3e4d66a2e9cd5f0eb8215b3d8845f15c9fbe8970
