### ISSUE TITLE
Score difference flashing

### ISSUE THREAD

**Issue by shrublet** [Hoshikara/Nightfall#6]
(Sorry for opening so many issues btw, just reporting bugs as I come across them) Seems to be an issue across skins with this feature, so I'm not sure it's possible to fix, but the score difference will consistently flash on every note as it draws the difference first before updating the score from the last note hit. At the very least, I don't think it's due to refresh as it occurs using both 60hz and 144hz. 
![nightfall_scorediff](https://user-images.githubusercontent.com/63182228/101292937-73750300-37c7-11eb-9cc6-0f08d3cfe449.gif)

**Comment by Hoshikara** [comment]
no worries, I'll look into this to see if I can make the flicker less distracting if it can't be fixed

**Comment by Hoshikara** [comment]
can't be fixed unfortunately
