### ISSUE TITLE
At 0 VF charts erroneously labeled Best 20/50 

### ISSUE THREAD

**Issue by shrublet** [Hoshikara/Nightfall#7]
This is a pretty edge-case scenario that I encountered on a fresh build of USC. At 0 VF without any  previous scores, up to 50 charts will have these labels. I'm not sure which order the skin goes through in determining if there should be a label, but afterwards I tested with less than 50 charts total in which they will all have either Best 20/50.

**Comment by Hoshikara** [comment]
Addressed in https://github.com/Hoshikara/Nightfall/commit/f1e94feb985cbb30fb3167eee087f26106b3a910
